### ISSUE TITLE
Article disappear from output control

### ISSUE THREAD

**Issue by shivharis** [superdesk/superdesk-publisher#96] opened 2019-01-30 21:23 UTC
I looked through the logs and below change seems related. The issue persists.

commit 87df77a42b9aede61fed8eb9588343246e66d3ef
Author: Tomasz Rondio <tomasz.rondio@gmail.com>
Date:   Wed Jan 23 13:41:24 2019 +0100

    fix: Once an article is updated and published it disappears from publish section of output control

**Comment by takeit** [comment] 2019-01-31 14:11
@tomaszrondio can you take a look?

**Comment by tomaszrondio** [comment] 2019-01-31 14:18
Have U updated to latest version from master? Checked minute ago and I cannot reproduce.

**Comment by shivharis** [comment] 2019-01-31 17:38
I am using latest from master.

Here is how I see the problem:
1. Ingest from Forbes
2a. Publish without specifying destination - Article in desk shows published does not appear in 'incoming'
2b. Publish with destination - Article in desk shows published, does not appear in published

**Comment by shivharis** [comment] 2019-01-31 19:10
npm installs:

superdesk-core@1.28.0  (git://github.com/superdesk/superdesk-client-core.git#dba963fd88514a6466b2a0bd4c09b18270a4ccf0)

superdesk-publisher@1.3.1  (git://github.com/superdesk/superdesk-publisher.git#b4db4176cfb8bc39e4aa6e0a969242f0dc51b10e

These both seem to be both master as of today

**Comment by takeit** [comment] 2019-02-01 08:35
@shivharis it could be related to this PR: https://github.com/superdesk/web-publisher/pull/711

which commit is your Publisher instance at?

**Comment by ahilles107** [comment] 2019-02-01 08:46
Yep, if in Superdesk Publish Queue you have `success` and articles is not visible in publisher API's, and You use latest 1.4 then most probably consumer isn't running. Sorry for that BC - we had to do this because of performance improvements for migrated customer. We will release 1.5 soon with BC descriptions.

**Comment by shivharis** [comment] 2019-02-01 12:30
As I said in 2a above:

 "Publish without specifying destination - Article in desk shows "published" does not appear in "incoming queue"

Is the web-publisher still involved when publishing without a specific destination? I am not talking about the act of publishing with actual site destination supplied. It disappears from 'incoming queue'

**Comment by ahilles107** [comment] 2019-02-01 12:33
Incomming and published are both managed in publisher. When content is pushed from superdesk it lands in publihser and there can be assigned to website (tenant) and route.

**Comment by shivharis** [comment] 2019-02-01 12:36
Thanks will wait for 1.5.

**Comment by ahilles107** [comment] 2019-02-01 12:38
Imo, You can play with 1.4 (latest commit). You can find required consumer config here: https://github.com/superdesk/web-publisher/blob/1.4/scripts/supervisor/supervisor_content_push.conf

**Comment by shivharis** [comment] 2019-02-01 13:16
Thanks.

**Comment by shivharis** [comment] 2019-02-01 21:42
The suggestion above did not solve the problem. I also incorporated the fix in supervisor_content_push.conf. No luck.

**Comment by ahilles107** [comment] 2019-02-02 08:19
Thing is that queue is created by consumer. Run consumer (by supervisor, or manually) remember about running it in correct env (`--env=prod` when you use production endpoint is subscriber settings). Then try to publish content again (you can even resend it from publishing queue).

**Closed** 2019-02-18 07:59 UTC
